-- CreateTable
CREATE TABLE "public"."job_data" (
    "id" TEXT NOT NULL,
    "user_id" TEXT NOT NULL,
    "content" TEXT NOT NULL,
    "title" TEXT,
    "company" TEXT,
    "status" TEXT NOT NULL DEFAULT 'uploaded',
    "processing_status" TEXT NOT NULL DEFAULT 'uploaded',
    "processing_started_at" TIMESTAMP(3),
    "processing_completed_at" TIMESTAMP(3),
    "processing_error" TEXT,
    "processing_time" INTEGER,
    "model_used" TEXT,
    "parameters" JSONB,
    "error_message" TEXT,
    "analysis_id" TEXT,
    "analysis_version" TEXT,
    "extracted_skills" JSONB,
    "required_qualifications" JSONB,
    "preferred_qualifications" JSONB,
    "job_type" TEXT,
    "location" TEXT,
    "remote_type" TEXT,
    "salary_range" TEXT,
    "experience_level" TEXT,
    "industry" TEXT,
    "department" TEXT,
    "employment_type" TEXT,
    "view_count" INTEGER NOT NULL DEFAULT 0,
    "last_analyzed_at" TIMESTAMP(3),
    "analysis_count" INTEGER NOT NULL DEFAULT 0,
    "is_public" BOOLEAN NOT NULL DEFAULT false,
    "retention_date" TIMESTAMP(3),
    "gdpr_consent" BOOLEAN NOT NULL DEFAULT false,
    "is_active" BOOLEAN NOT NULL DEFAULT true,
    "data_classification" TEXT,
    "is_archived" BOOLEAN NOT NULL DEFAULT false,
    "archive_date" TIMESTAMP(3),
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "job_data_pkey" PRIMARY KEY ("id")
);

-- AddForeignKey
ALTER TABLE "public"."job_data" ADD CONSTRAINT "job_data_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "public"."profiles"("user_id") ON DELETE CASCADE ON UPDATE CASCADE;
